#!/usr/bin/env bash

# Git for windows uses its own Windows port for bash and it interprets the shebang. However, the path to bash/sh needs to be changed.
# Example
# #!C:/path/to/Git/bin/sh.exe

# set -x

root_path=$(git rev-parse --show-toplevel)
all_files=false

for arg in "$@"; do
    case $arg in
        --all )all_files=true
            shift;;
    esac
done

if $all_files; then
    file_list=$(git ls-tree -r HEAD --name-only)
else
    file_list=$(git diff --cached --name-only)
fi

found_abs_path=false

for file in $file_list; do
    if [ -f "$file" ]; then
    matches=$(grep -nE --color=always '(["'\''`])(/[^[:space:]]+|[A-Za-z0-9._]:([/\\]|\\\\)[^[:space:]]*)\1' "$file")
        if [ ! -z "$matches" ]; then
            echo "$matches"
            found_abs_path=true
        fi
    fi
done

if [ ! $all_files ]; then
    if $found_abs_path; then
        echo "Commit aborted due to absolute paths."
        exit 1
    else
        echo "No absolute paths found commit proceeding"
        exit 0
    fi
else
    exit 0
fi

